#cloud-config
hostname: ultron-db
users:
  - default
  - name: attacker
    groups: [users]
    shell: /bin/bash
packages: [postgresql, openssh-server]
write_files:
  - path: /etc/ultron/profile.json
    permissions: "0644"
    content: '{"profile_id":"db","misconfig_ids":[]}'
runcmd:
  - [systemctl, enable, postgresql]
  - [systemctl, enable, ssh]
