set -g default-terminal "tmux-256color"
set -g history-limit 200000
set -g mouse on
set -g destroy-unattached off
set -s exit-empty on
set -g remain-on-exit on
set -g status-interval 2
set -g status-left-length 48
set -g status-left "[#S] "
set -g status-right "#{pane_current_command} #{?pane_dead,DEAD,running}"
set -g set-titles on
set -g set-titles-string "ultron:#S"
